project:
  title: "2020 Political Tweets"
  output-dir: _products
  execute-dir: project
  pre-render: 
    - utils/check_packages.R      # install required packages
    - utils/remove_artifacts.ts   # remove previously constructed files
  render:
    # if analysis is split into multiple docs, add them here
    - analysis/organize_data.qmd
    - analysis/analysis.qmd
    - paper/
    - presentation/
    - "!bibliography/"

author:
  - name: Zane Arky
    orcid:
    email: zanea@uoregon.edu
    url: 
    attributes:
      corresponding: true
    affiliations:
      - id: uo
        name: University of Oregon
        department: Sociology
        address: 
        city: Eugene
        region: OR
        country: USA
        postal-code: 97405
  
execute: 
  freeze: false
  
editor: source



