---
title: "Paper Manuscript"
shorttitle: "Paper"
abstract: An Abstract
keywords: [keyword1, keyword2]
thanks: Thanks to everyone for checking this out.
reference-section-title: References
bibliography: ../bibliography/project.bib
csl: ../bibliography/chicago-parenthetical.csl
format:
  aog-article-pdf:
    keep-tex: false
    include-in-header: 
      text: |
        \usepackage{dcolumn}
#  submittable-pdf:
#     keep-tex: false
#     fig-pos: "!t"
#     include-in-header: 
#       text: |
#         \usepackage{dcolumn}
  submittable-docx: default
---

```{r}
#| label: setup
#| include: false
library(here)
source(here("utils","check_packages.R"))
source(here("utils","functions.R"))
```

# Introduction

Since its emergence in 2006, the social networking site (SNS) Twitter has transformed from a microblogging platform into a socially and culturally diverse space offering public discourse, political commentary, and real-time news coverage and dissemination, and this space is accessed by individuals on a global scale. What makes this space more unique from other SNS sites which don’t have politics as a primary function, is that as a space for public discourse and critical engagement with real current events, the discourse is often dictated between people who otherwise would not be connected in such subjects. The algorithm that pushes the directions of the discourse relies on a complex set of interactions that are triggered on the part of the users. In the current day, SNS platforms are primary and widespread avenues through which to access public discourse, however, Twitter is unique in how much power the user has in structuring this discourse.  In this paper we ask specifically: 
1. How do specific narratives converge in echo chambers around major events?
2. To what extent do addressivity markers contribute to or facilitate narrative alignment within distinct ideological spaces?
3. How does framing of a major event over time shift within these echo chambers?

It is important to ask these questions to understand how public discourse forms, operates and moves to formulate current events. There has been much research on the social impact of SNS platforms, particularly Twitter and its sensationalist attitudes. On Twitter, users have always played a fundamental and organic role in shaping how content is organized on the platform. Hashtags were initially created and used by users to organize content before they became an integral organization of feeds. In addition to hashtags, social networks between users themselves are organized on Twitter through tokens such as addressivity markers and text, all of which originate from an interaction between users. Retweets are another important use of creating and establishing networks. Whereas likes function as individual engagements effect feeds on an individual level, retweets function as endorsements and work as social cues to enhance a particular idea in a social framework.

Past research has outlined how we define echo chambers and methods of identifying them through content and network analysis. Much has been contributed particularly to how political echo chambers function in the circulation of ideas and ideologies, to distinguish the impact it has on the broader way people think, and the lens politics has been perceived in public discourse. Because of the way the data in this study was collected, we will be building off methods of content analysis to identify echo chambers. The goal of this paper will be to extend that prior research to formulate how echo chambers function and interact with developing events, examining how echo chambers react in the real-time news dissemination of a heavy or important current event. We aim to determine who and what gets mentioned, and how a narrative is developed or develops over time. Specifically, we are interested in how the framing of an issue reacts to shifts in sentiment or reaction to new information. Additionally, we want to determine addressivity markers that become popular around certain events and determine if this is a cause of any overlap in narrative similarity between different spaces across the political spectrum.


# Background

# Data and Methods

The dataset in this paper consists of 950000 tweets collected between October 15th, 2020 to November 8th, 2020, during the final weeks leading up to and the week after the 2020 US Presidential Election.  The tweets were collected using the Twitter API statuses_lookup and snsscrape for keywords. The data were scraped by a third party and are publicly available on Kaggle: [US Election 2020 Tweets](https://www.kaggle.com/datasets/manchunhui/us-election-2020-tweets/data).

Observations in the dataset represent tweets which mentions either "Biden" or "Trump" in the tweet text. The dataset contains 21 columns and records metadata such as tweet text, timestamp, user ID, and various engagement metrics like follower count, likes, and retweets. However the dataset does not include edge data between users, so it is better suited for sentiment analysis rather than social network analysis.

The data captures a wide range of political discourse of the election across languages and countries, however the scope of the data is limited to the keywords of the political candidates that the data were scraped on, so it is not fully representative of the political discourse in the weeks surrounding the election, neither is it a representative sample of political tweets and twitter activity more broadly. Additionally, the dataset is limited to tweets public available for scraping.

# Results

# Conclusions
